// Claude says these are ~35 french nouns with their associated gender.

const wordsToCheck = [
    { word: "chat", gender: "masculine" },
    { word: "table", gender: "feminine" },
    { word: "livre", gender: "masculine" },
    { word: "pomme", gender: "feminine" },
    { word: "soleil", gender: "masculine" },
    { word: "maison", gender: "feminine" },
    { word: "arbre", gender: "masculine" },
    { word: "fleur", gender: "feminine" },
    { word: "temps", gender: "masculine" },
    { word: "voiture", gender: "feminine" },
    { word: "garçon", gender: "masculine" },
    { word: "fille", gender: "feminine" },
    { word: "chien", gender: "masculine" },
    { word: "chaise", gender: "feminine" },
    { word: "pain", gender: "masculine" },
    { word: "eau", gender: "feminine" },
    { word: "téléphone", gender: "masculine" },
    { word: "fenêtre", gender: "feminine" },
    { word: "ordinateur", gender: "masculine" },
    { word: "porte", gender: "feminine" },
    { word: "stylo", gender: "masculine" },
    { word: "école", gender: "feminine" },
    { word: "jardin", gender: "masculine" },
    { word: "cuisine", gender: "feminine" },
    { word: "lit", gender: "masculine" },
    { word: "ville", gender: "feminine" },
    { word: "café", gender: "masculine" },
    { word: "chemise", gender: "feminine" },
    { word: "vélo", gender: "masculine" },
    { word: "lune", gender: "feminine" },
    { word: "restaurant", gender: "masculine" },
    { word: "mer", gender: "feminine" },
    { word: "train", gender: "masculine" },
    { word: "montagne", gender: "feminine" },
    { word: "jouet", gender: "masculine" },
    { word: "forêt", gender: "feminine" },
]

export { wordsToCheck }
